services:
  - type: web
    name: workvix-backend
    runtime: python
    pythonVersion: 3.13.4
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: workvix-backend-rb7p.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: workvix_project.settings
