services:
  - type: web
    name: workvix-backend
    runtime: python
    pythonVersion: 3.13.4
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn workvix_project.wsgi:application --bind 0.0.0.0:10000 --workers 4 --timeout 120 --access-logfile - --error-logfile - --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: workvix-backend-rb7p.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: workvix_project.settings
      -