services:
  - type: web
    name: workvix-backend
    runtime: python
    pythonVersion: 3.13.4
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn workvix_project.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --access-logfile - --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: workvix-backend-rb7p.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: workvix_project.settings
